### ISSUE TITLE
Having trouble installing Bonfire

### ISSUE THREAD

**Issue by Rambo8000** [ci-bonfire/Bonfire#1024]
I'm trying to install Bonfire for Codeigniter and I'm having some issues. I first tried downloading the zip, unziping it and placing it in MAMP and navigating to it through localhost. The welcome page came up but when I clicked on the "install" button, it displayed a "URL Not Found" page. Quite annoying since I'm under the gun.

I saw on youtube, that the dev team shows the install by cloning the repo on Github so I tried that next. Now when I load that in my localhost, I get a welcome page without an install button, an error saying my "htaccess" should be renamed ".htaccess" (although when I looked at the file it looked fine to me) but more worryingly is the next error:

"Oops! Your Web Root should be set to the public folder,but it's not. It's pointing to the Bonfire Root folder.

See below how your site should be set up on Apache:

<VirtualHost *:80>
    DocumentRoot "[...]/htdocs/Bonfire_Root/public"
    ServerName Bonfire.Root
    ServerAlias Bonfire.Root.local
</VirtualHost>"
I'm a really junior programmer and I'm just trying to get this sorted out quickly because of a project I'm on that I need to turn around quickly. I'm sure this is probably something simple so does anyone know what I can do to fix this so it will work and I can begin developing with Bonfire? Thanks in advance!

EDIT:

When I followed the instructions about adding my project name to the URL, I moved on to a blank page, Chrome initiated a download of a textfile called install which contains this:

J 5.5.34B:;Z1&hZˇ˜Äj*/Knh@G"o/9mysql_native_password!ˇÑ#08S01Got packets out of order

I'm not sure what to do with this. Any ideas?

I've tried:

http://localhost/Bonfire_Root/public/

http://localhost/Bonfire_Root/public/index.php

http://192.xxx.xxx.xxx/Bonfire_Root/public/index.php
Each time it just downloads the textfile with the same text in it. :/

**Comment by ilemonajames** [comment]
How do I point it the index file?

**Comment by kjwm** [comment]
You edit the virtual hosts to point to your project public folder as @mwhitneysdsu directed.

**Comment by mrsundaymonday** [comment]
Checkout this link video (problem solved):

https://www.youtube.com/watch?v=RIM0_mHvJDU
