### ISSUE TITLE
Email sending test make subnav bar crash

### ISSUE THREAD

**Issue by juju95** [ci-bonfire/Bonfire#1033]
When you enter your mail and click on Send Test Mail, the loaded page has the right sub nav masked under the title

( Not an important thing but i'm not a good git user so i can't send commits ;) )

**Comment by mwhitneysdsu** [comment]
In case someone is looking for a solution for a similar issue, the fix for this was to set the toolbar_title in the controller: Template::set('toolbar_title', 'Title goes here');
