### ISSUE TITLE
Corrections for the Simple Blog Tutorial

### ISSUE THREAD

**Issue by surfmunkey** [ci-bonfire/Bonfire#1067]
Just learning Bonfire, and found the following issues in the Simple Blog Tutorial (which is an excellent tutorial, by the way):

1) The very last section of code in this tutorial (this is for the blog/views/index.php file) is missing the following first two lines:

 <?php if (isset($posts) && is_array($posts)) :?>
        <?php foreach ($posts as $post) : ?>

A couple other minor corrections:
2) First paragraph has a bad link to the Module Builder - this leads to a File not Found error (nothing really to do with learning the tutorial, but just a error on the website).

3) Under the section subtitled "Saving the Post" - just a typo in the second paragraph that says "pose_model", should say "post_model".

**Comment by JanderCleisson** [comment]
OK thank you
