### ISSUE TITLE
Simple Blog tutorial - missing 'delete posts' functionality...

### ISSUE THREAD

**Issue by surfmunkey** [ci-bonfire/Bonfire#1068]
Recently finished the Simple Blog tutorial, as my first dip of the toe into using Bonfire.  Excellent tutorial, and is only missing the functionality for deleting the checked posts.

Other than the above, this tutorial is complete and covers a lot of very useful functionality.  Have seen several unanswered posts regarding this same subject over the years, and I'm guessing the solution is fairly straight forward.  Would be great to see the tutorial completed for all us newbies coming on board.

Thank you.

**Comment by girvile** [comment]
The website is down, but you can find the topic here : 
http://web.archive.org/web/20150506015737/http://forums.cibonfire.com/discussion/951/update-on-blog-examples-in-new-documentation/p1?post
