### ISSUE TITLE
Set Custom Error messages per rule for Form Validation

### ISSUE THREAD

**Issue by umairayub** [ci-bonfire/Bonfire#1098]
I am having trouble setting my custom Error Messages upon Form Validations for every Rule.

I have tried it from Bonfire documentation here (http://ci3docs.cibonfire.com/libraries/form_validation.html#setting-rules-using-an-array)

Here is some code of my Model of a Module

    class Content_management_system_model extends BF_Model {
    
        protected $table_name = 'article';
        protected $key = 'id';
       
        // be updating a portion of the data.
        protected $validation_rules = array(
             array(
                'field' => 'article_alias',
                'label' => 'lang:content_management_system_article_alias',
                'rules' => 'unique[article.article_alias,article.id]',
                'errors' => array(
                    'unique' => 'This is my custom error',
                ),
            ),
          
And here the rules are being set from Admin Controller when Inserting

    private function save_content_management_system($type = 'insert', $id = 0) {
          
            // Validate the data
            $this->form_validation->set_rules($this->content_management_system_model->get_validation_rules());
            if ($this->form_validation->run() === false) {
                return false;
            }

But it always shows default message `The value in "Article Alias" is already being used.` 

As per documentation in mentioned link, it should show error `This is my custom error`

**Comment by mwhitneysdsu** [comment]
I'm not quite sure how you got to that link, but you're looking at the documentation for CodeIgniter v3.

The Bonfire docs for setting up validation in the model are found at http://cibonfire.com/docs/developer/bonfire_models#validation (or, if you have Bonfire installed as localhost, the docs for the version of Bonfire you have installed should be accessible via http://localhost/docs/developer/bonfire_models#validation ). The CodeIgniter documentation for the Form_validation library which is used by the current version of Bonfire is available at http://www.codeigniter.com/user_guide/libraries/form_validation.html

With CodeIgniter 2.2.1, I don't think error messages can be set the way you are attempting to set them, even if Bonfire was passing the errors key to the form validation library.

**Comment by umairayub** [comment]
Thanks ... I just checked I am using CI 2.2.0.

And I am sure I cannot set validation error messages through specifying in Model ..

**Comment by mwhitneysdsu** [comment]
The changes from 2.2.0 to 2.2.1 should be minimal as far as the form_validation library is concerned. You should be able to change the error messages by calling the form_validation library's set_message method. http://www.codeigniter.com/user_guide/libraries/form_validation.html#settingerrors
