### ISSUE TITLE
Installation using CI 3.0 as default fails

### ISSUE THREAD

**Issue by silverark** [ci-bonfire/Bonfire#1103]
I tried using the installation script for bonfire after downloading and switching the $system_path to CI3. This gave the following error: "Table 'leadamo3.bf_ci3_sessions' doesn't exist"

Is there a way of not loading the sessions library until the installation has completed for CI3 as the database to hold the sessions isn't available yet.

**Comment by mwhitneysdsu** [comment]
At this time, the best thing to do is to install everything using CI2, then switch it over to CI3.

Installation under CI3 is definitely something we need to support, though, so I intend to keep this issue open until it has been addressed.

**Comment by mwhitneysdsu** [comment]
Have you tried removing session from $autoload['libraries'] in /application/config/autoload.php? I still have to trace through the code which runs during installation, but the installer itself doesn't use sessions directly.

**Comment by mwhitneysdsu** [comment]
While that may (or may not) help in the long run, the problem is actually the pre_controller hook which calls App_hooks->saveRequested(), so I'm trying to figure out whether the saveRequested() method can be setup to work properly during installation.
