### ISSUE TITLE
New Role Permissions / Matrix

### ISSUE THREAD

**Issue by jamiegamauf** [ci-bonfire/Bonfire#1104]
I have fresh install of Bonfire.  I can create new roles but cannot assign permissions.  After the role is created, it does not appear in the Permissions Matrix either.

![bonfire-newrole](https://cloud.githubusercontent.com/assets/6267059/7402237/40562cac-ee98-11e4-893b-6223b2f4f4c8.png)

![bonfire-newrole2](https://cloud.githubusercontent.com/assets/6267059/7402293/ace22362-ee98-11e4-8b1e-6554890b4b9e.png)

**Comment by jamiegamauf** [comment]
The issue appears to be that it does not recognize that I have permission even though I am logged in as the Admin.

**Comment by jamiegamauf** [comment]
Ok, solving this as I go.  When the New Role is created, a new Permission is NOT created.  I had to create a new permission and then assign that to Admin in order to see the new role in the matrix.

**Comment by mwhitneysdsu** [comment]
5a1c1b9d1d0dfa95000370b5da6f35b101e0d587
