### ISSUE TITLE
No $this->{model}->error is generated for a failed update due to duplicate (index) key error

### ISSUE THREAD

**Issue by disccomp** [ci-bonfire/Bonfire#1107]
Steps to reproduce:
Model uses a Table with a two-field unique index(a, b)

id a b
1 1 1
2 1 2
Now edit row 2 and change b to 1, hit save. Edit page is reloaded with no error. Because $this->{model}->update returns false with no error message set.

**Comment by mwhitneysdsu** [comment]
Note that you should have validation in place for a two-field unique index, but you are right that the model should return an error message from the database when the operation fails.
