### ISSUE TITLE
libraries bonfire not loaded

### ISSUE THREAD

**Issue by didiwijaya** [ci-bonfire/Bonfire#1110]
../bonfire/libraries not loaded. I have tried master branch and newest develop branch, but all the same, bonfire/libraries not loaded. 
For example : bonfire/libraries/BF_Form_validation, bonfire/libraries/Assets.
unique, valid_password, add_module_js, add_css can not be used.

please, give solution !

**Comment by mwhitneysdsu** [comment]
The two libraries you've mentioned are autoloaded by the Authenticated_Controller, which is located in /application/core/Authenticated_Controller.php. What is the exact error message you are getting, and on what page(s)?

**Comment by didiwijaya** [comment]
I know, the two libraries are autoloaded in authenticated_controller. 
But bonfire/libraries/BF_Form_validation not loaded by BF_Loader (bonfire/core/bf_loader), BF_Loader only load Form_Validation (CI_Form_validation).
Please, check module users, when create or update, unique and valid_password not working.

**Comment by donowp** [comment]
Little bit tricky but it works for me... create file MY_Form_validation.php in /application/libraries. Fill file with this code.
 
class MY_Form_validation extends BF_Form_validation
{
    /**
     * @var object The CodeIgniter core object.
     */
    public $CI;
}

**Comment by didiwijaya** [comment]
it works, thanks

**Comment by mwhitneysdsu** [comment]
I'll have to take another look at this. The MY_Form_validation.php file should not be required. This was tested and working when MY_Form_validation was originally renamed to BF_Form_validation, but it's possible that a modification made to the CI2 core wasn't properly migrated to CI3.

Are you still having issues with the Assets library?

**Comment by mwhitneysdsu** [comment]
The version of the Authenticated_Controller in develop actually makes this issue more critical, as you should get the following error message:

```
Fatal error: Cannot access protected property CI_Form_validation::$CI in /var/www/testcbaweb/application/core/Authenticated_Controller.php on line 35
```

The modification to BF_Loader included in the above commit should take care of this issue, but I figured it would be best to get some feedback before closing it out.

**Comment by didiwijaya** [comment]
No, Assets library no issue. Thanks.
