### ISSUE TITLE
Parse error: syntax error, unexpected ',' in /home/mailsp7/public_html/bonfire/application/modules/auditlog/views/content/create.php on line 25

### ISSUE THREAD

**Issue by xoco70** [ci-bonfire/Bonfire#1116]
Hi, 

After successfully generate module, all create operation gives me that error. It seems that the generated code contains errors.

I want to use bonfire to start a new project, but I can't test it without resolving it :( 

Any idea?

**Comment by mwhitneysdsu** [comment]
To help narrow down the cause of the issue, what options were used when generating the module?

**Comment by samerkamel** [comment]
@xoco70 in bonfire/modules/builder/views/files/view_default.php
there is an extra "." on line 32

Replace
    // Validation rules for this fieldset
    if (is_array($validation_rules)) {
        foreach ($validation_rules as $key => $value) {
            if ($value == 'required') {
                $required = ". lang('bf_form_label_required')";
                $required_attribute = true;
            }
        }
    }

with : 
    // Validation rules for this fieldset
    if (is_array($validation_rules)) {
        foreach ($validation_rules as $key => $value) {
            if ($value == 'required') {
                $required = " lang('bf_form_label_required')";
                $required_attribute = true;
            }
        }
    }


Worked for me :)

**Comment by samerkamel** [comment]
On a windows installation i found that i had to go through the whole switch case in the same file to remove very weirdly placed dots into a double quote string. 

Sorry i am not a git user so not sure how to flag this post for review and consider it as a solution..

**Comment by mwhitneysdsu** [comment]
I have a feeling this is still not right... It would be nice if we could get this down to the point that it was easier for people to customize the output of the builder.
