### ISSUE TITLE
Initial Migration Tutorial

### ISSUE THREAD

**Issue by j0nr** [ci-bonfire/Bonfire#1122]
Hey folks, I am having a try at installing Bonfire and I am just working through the "blog example" in the docs and have got stuck at one of the first hurdles.

I have created the modules>blog>migrations>001_Initial_tables.php file, which I can then find in the Developer>database>migrations menu...but when I select 001_Initial_tables to migrate it comes up with an error:

*There was an error migrating the database.
Migration class does not exist: Migration_Initial_tables*

I'm stuck...how do I proceed please?

Thanks.

**Comment by mwhitneysdsu** [comment]
Check your spelling and capitalization on both the class name and the file name. Although I don't think it's an issue at this specific point in the tutorial, I would also recommend that you use either the version included when you downloaded Bonfire (by navigating to the docs directory on your development site) or here on Github: https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/tut_blog.md

**Comment by wywywywy** [comment]
The first line should be this and it's missing in the tutorial.

`<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');`

**Comment by mwhitneysdsu** [comment]
As I mentioned in the post above (a year ago), use the version downloaded with Bonfire or the version here on GitHub: https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/start_here/tut_blog.md

If the first line is still missing, please open a new issue and specify where in the tutorial it is missing.
