### ISSUE TITLE
Module Builder - 404

### ISSUE THREAD

**Issue by spudatron** [ci-bonfire/Bonfire#1129]
Hey,

I just installed 0.8 of bonfire on a production server and when I create a new module using the module builder everything works fine, there are no errors in the process but when I attempt to view the module I get a 404 error. I have the same installation on my localhost but don't have the same problem. I would assume it might be a permissions issue but comparing my production environment with my localhost they are the same. 

Any ideas where this issue could be?

**Comment by mwhitneysdsu** [comment]
I have a feeling that Module Builder is probably not building the files (especially controllers) with the proper capitalization in the filenames, but the loader and router should still allow this to work. In any case, it's worth checking the capitalization of both the class names and filenames, as both should be ucfirst for CI3, though Bonfire's router and loader should allow them to be lowercase as well (for now).

Additionally, if you're creating new contexts with the builder, you may need to add routes for those contexts.

**Comment by spudatron** [comment]
Cheers Mat, that was it, all the controllers were lower case and the class in the main controller with the same name as the module was also lower case. Changed all to upper case and its working now. Thanks for your help.

**Comment by mwhitneysdsu** [comment]
No problem. I'm going to re-open this issue, though, to serve as a reminder to fix this in the Builder code.

**Comment by spudatron** [comment]
Ok, cool.
