### ISSUE TITLE
modules_locations array not loaded in application.php

### ISSUE THREAD

**Issue by marzsman** [ci-bonfire/Bonfire#1131]
When I add or change a path in the modules_locations array in /config/application.php my modules aren't loaded and I get a 'Unable to load your default controller.' error.
To make it work I had to move the array to the main config.php file. 

It's like the application.php file is not loaded early enough.

**Comment by mwhitneysdsu** [comment]
Do you have the following in your `/application/config/autoload.php`?
`$autoload['config'] = array('application');`

**Comment by marzsman** [comment]
Yes, and the file is also loaded. 
But the moment I move the array back into the application.php config the site wont load

**Comment by mwhitneysdsu** [comment]
I'll take a look at it when I get a chance. It sounds like it may just have to be moved to `/application/config/config.php`, but there may be some possibility that something can be changed in the Modules library to get it working in `/application/config/application.php`.
