### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by islamicwavez** [ci-bonfire/Bonfire#1134]
during installation login page not found

**Comment by mwhitneysdsu** [comment]
I'm afraid I'll need more information to be able to help you. Installation is basically a single page which tells you whether or not the basics are configured correctly (database configuration, write access, etc.). See the [Installing Bonfire](https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/installation.md) section of the documentation. You wouldn't normally go to the login page until after you've completed installation.
