### ISSUE TITLE
Error building a new module on Bonfire v0.8.2-dev

### ISSUE THREAD

**Issue by gianni72** [ci-bonfire/Bonfire#1142]
When I try to build a new module I get this error:

A PHP Error was encountered

Severity: Notice

Message: Undefined property: Modulebuilder::$load

Filename: libraries/Modulebuilder.php

Line Number: 696

Backtrace:

File: /var/www/panel/bonfire/modules/builder/libraries/Modulebuilder.php
Line: 696
Function: _error_handler

File: /var/www/panel/bonfire/modules/builder/libraries/Modulebuilder.php
Line: 326
Function: buildView

File: /var/www/panel/bonfire/modules/builder/controllers/Developer.php
Line: 638
Function: buildFiles

File: /var/www/panel/bonfire/modules/builder/controllers/Developer.php
Line: 202
Function: build_module

File: /var/www/panel/public/index.php
Line: 314
Function: require_once

Fatal error: Call to a member function helper() on a non-object in /var/www/panel/bonfire/modules/builder/libraries/Modulebuilder.php on line 696
A PHP Error was encountered

Severity: Error

Message: Call to a member function helper() on a non-object

Filename: libraries/Modulebuilder.php

Line Number: 696

Backtrace:

**Comment by mwhitneysdsu** [comment]
Thanks for letting us know.
