### ISSUE TITLE
Convert your HTML data tables on Highcharts graphs

### ISSUE THREAD

**Issue by manieqq** [ci-bonfire/Bonfire#1145]
My suggestion is to include the plugin in admin panel to generate graphs from HTML tables, because you know how it is sometimes difficult.

http://highcharttable.org/

**Comment by mwhitneysdsu** [comment]
Feel free to do this on your own, but I won't be putting something into the repository that could potentially cost money for anyone that uses the feature.

https://shop.highsoft.com/highcharts.html
