### ISSUE TITLE
Raport PDF, CSV, XLS 

### ISSUE THREAD

**Issue by manieqq** [ci-bonfire/Bonfire#1146]
Is it possible to install plugins to generate reports in PDF, CSV, XLS? Sometimes we need to pull some data from the database and save to a file and it's easier to our lives. What do you think?

Is it possible to put the library dompdf
https://github.com/dompdf/dompdf

**Comment by mwhitneysdsu** [comment]
You should be able to follow their instructions to install their plugin and use it in your reports. Personally, I use a couple of different libraries for custom reports, depending on the needs of the report in question. For example, I use DataTables and [TableTools](http://datatables.net/extensions/tabletools/) for cases in which people just want to export the HTML table to PDF/Excel, but I've used [PHPExcel](https://github.com/PHPOffice/PHPExcel) for a couple of cases in which a more specific format was required explicitly for an Excel report.
