### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by FoxMiner** [ci-bonfire/Bonfire#1148]
bonfire can not be installed on a clean installation

A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

SHOW TABLES FROM

Filename: .../bonfire/modules/migrations/libraries/Migrations.php

Line Number: 728

**Comment by mwhitneysdsu** [comment]
I pulled down a clean copy of the code and configured `/application/config/development/database.php` to point to an empty database. The install page came up and I made some directories writable which the installer indicated were not, then continued through the installation routine without issues.

I dumped the database, removed `/application/config/installed.txt`, and removed `$config['bonfire.installed'] = "1";`, then configured  `/application/config/development/database.php` to point to a non-existent database, and got the following errors:

```
A PHP Error was encountered
Severity: Warning
Message: mysqli::real_connect(): (42000/1049): Unknown database 'test_cochimetl_'
Filename: mysqli/mysqli_driver.php
Line Number: 135
Backtrace: {backtrace omitted}
```

```
A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: third_party/MX/Base.php
Line Number: 55
```

When I decided to try the Mythbusters approach of doing something I thought would replicate the results even though it shouldn't be done in the real world, I still didn't get the same result:

```
An Error Was Encountered
A table name is required for that operation.
```

This error was received when I set the table name to an empty string in the $migrationsTable property of `/bonfire/modules/migrations/libraries/Migrations.php`.

So, I'm not sure what's different on your end that's causing that error. Did you change anything other than `/application/config/development/database.php`?

**Comment by Jojr** [comment]
You need to setup the Database configuration file first.

Go to "application/config/database.php" and setup your database connection.
[https://ellislab.com/codeigniter/user-guide/database/configuration.html]

Then start your Bonfire Setup again.

This work for me.
