### ISSUE TITLE
Bonfire does not set the default 'modified_on'!!!

### ISSUE THREAD

**Issue by xh84** [ci-bonfire/Bonfire#1149]
i use Bonfire 0.8.1 master
i follow "A Simple Blog Tutorial", and set:

    protected $set_created  = true;
    protected $set_modified = true;
    protected $soft_deletes = true;
    protected $date_format  = 'datetime';

there are fields 'modified_on' and 'created_on' in my mysql database

when i creat new post, i get errors:

A Database Error Occurred
Error Number: 1364
Field 'modified_on' doesn't have a default value
INSERT INTO `bf_posts` (`title`, `slug`, `body`, `created_on`) VALUES ('it is a test', 'it-is-a-test', 'it is a test!!!', '2015-07-25 17:27:49')
Filename: D:/upupw/htdocs/Bonfire-master/bonfire/core/BF_Model.php
Line Number: 480

**Comment by mwhitneysdsu** [comment]
You should define your $modified_field with a default value of '0000-00-00 00:00:00' or define it as nullable. The $modified_field is only set on updates, because an insert is not a modification.

So, I guess the field definition in the tutorial needs to be updated accordingly.

**Comment by xh84** [comment]
i get it, thank you!!
