### ISSUE TITLE
Changing Role name breaks permissions

### ISSUE THREAD

**Issue by jhob101** [ci-bonfire/Bonfire#1150]
Bonfire v0.8.1-dev
CI 3

Changing the name of role breaks the permissions (e.g. change 'Editor' to 'Test').  Changing the name back again to the previous value fixes the issue.

I made a video to demonstrate the bug: http://screencast-o-matic.com/watch/cojeFcfxMU

**Comment by mwhitneysdsu** [comment]
So, this is going to require either:
- the way the permissions are associated with the roles will need to be changed, or 
- the name of the permission will have to be changed when the name of the role changes.

**Comment by mwhitneysdsu** [comment]
Well, apparently it's supposed to change the name of the permission when the name of the role changes, but it's not working...

**Comment by jhob101** [comment]
thanks for the quick fix!
