### ISSUE TITLE
[BF_Router] Call to undefined method _set_404override_controller()

### ISSUE THREAD

**Issue by mwhitneysdsu** [ci-bonfire/Bonfire#1151]
As reported by libregeek on the forums:
http://forums.cibonfire.com/discussion/2909/setting-default-controller-in-bonfire-0-8-1

```
Fatal error: Call to undefined method BF_Router::_set_404override_controller() in /var/www/html/demo/Bonfire-0.8.1/bonfire/core/BF_Router.php on line 262
A PHP Error was encountered

    Severity: Error
    Message: Call to undefined method BF_Router::_set_404override_controller()
    Filename: core/BF_Router.php
    Line Number: 262
```

**Comment by suwitolt** [comment]
The error has gone, but i think the problem exist. the question in the forum : 
http://forums.cibonfire.com/discussion/2909/setting-default-controller-in-bonfire-0-8-1

how to use admin area only. i have tried the step in the link question above :

[ So I changed the routing settings in application/config/routes.php to as follows:
$route['default_controller'] = 'content'; ]

The error has gone, but now produce 404.

**Comment by mwhitneysdsu** [comment]
In order to set the default controller to content, you have to have a controller in /application/controllers/Content.php. That's why I stated in that thread that there were two problems here: the bug in the router that caused the error to appear when the 404 message should have been displayed, and the setting of the default controller to a controller which could not be found.

My recommendation in that thread of setting it to 'admin' was also incorrect (and I'll note that in the thread shortly), because Bonfire doesn't come with an Admin controller.

**Comment by suwitolt** [comment]
Okey, thanks.
