### ISSUE TITLE
Cancel button in generated crud contains 'Content' instead of 'content'

### ISSUE THREAD

**Issue by dipu** [ci-bonfire/Bonfire#1154]
The Cancel button in generated crud contains 'Content' instead of 'content' and causes a "404 Page Not Found"

**Comment by mwhitneysdsu** [comment]
If you change line 174 of `/bonfire/modules/builder/views/files/view_default.php` from:

```php
            <?php echo anchor(SITE_AREA . '/{$controller_name}/{$module_name_lower}', lang('{$module_name_lower}_cancel'), 'class=\"btn btn-warning\"'); ?>
```

to:

```php
            <?php echo anchor(SITE_AREA . '/" . strtolower($controller_name) . "/{$module_name_lower}', lang('{$module_name_lower}_cancel'), 'class=\"btn btn-warning\"'); ?>
```

does it fix the problem?

**Comment by dipu** [comment]
@mwhitneysdsu thanks for your quick response. I am cloning it atm. I will check and update here.

**Comment by dipu** [comment]
The change you advised fixed the issue. Same issue is affecting the edit link url. I will make the changes and do a pull request.

Thanks

**Comment by dipu** [comment]
Made the changes, tested by creating new modules and created a pull request.
