### ISSUE TITLE
Validation message contains "form_validation_"

### ISSUE THREAD

**Issue by dipu** [ci-bonfire/Bonfire#1159]
Form validation message contains "form_validation_" and is prefixed to a field name.

For example, if the field name is customer_email, the message is "form_validation_customer_email" and it causes a FIXME('form_validation_customer_email')

I have tried changing this
    if (FALSE === ($fieldname = $this->CI->lang->line('form_validation_'.$line)) to
    if (FALSE === ($fieldname = $this->CI->lang->line($line))
and it works as expected.

I am not sure if it is a bug.

**Comment by mwhitneysdsu** [comment]
http://www.codeigniter.com/user_guide/installation/upgrade_300.html#step-18-update-your-form-validation-language-lines

I know that at least one of the bug fixes in CodeIgniter 3.0.1 was related to how the form_validation library was handling field names in 3.0.0. You should also make sure you're using 3.0.1, which would mean using Bonfire 0.8.3 (master), 0.8.4-dev (0.8-dev), or 0.9.0-dev (develop), or that you manually upgraded CI to 3.0.1 in your Bonfire project.

If there is some issue beyond what is addressed in that particular step of the upgrade instructions or the 3.0.1 update, it should probably be brought up on the [CodeIgniter forums](http://forum.codeigniter.com/). In some cases, we could probably address it in `/bonfire/libraries/BF_form_validation.php` (or you could address it in `/application/libraries/MY_form_validation.php`), but we try to do that as little as possible.

**Comment by dipu** [comment]
thanks @mwhitneysdsu for pointing out the issue. I should have found that in the codeigniter guide.
I am currently using bonfire 0.8.2 (manually upgraded). I will update to 0.8.3 too. Hopefully that will solve my issue.
