### ISSUE TITLE
Assets Library don't work with www.jsdelivr.com

### ISSUE THREAD

**Issue by FlorinMotoc** [ci-bonfire/Bonfire#1193]
If I'll put this:
```
<?php echo Assets::js('//cdn.jsdelivr.net/g/jquery.ui@1.11.4,bootstrap@3.3.6'); ?>
```

It will result in this:
```
<script src='//cdn.js' type='text/javascript'></script>
```

Probably this is because http://www.jsdelivr.com/ don't have a .js at the end of string, and Bonfire Assets Library will "cut" the string at the last .js it founds (that's in the domain name)

**Comment by mwhitneysdsu** [comment]
Does this happen when you call `echo Assets::external_js('//cdn.jsdelivr.net/g/jquery.ui@1.11.4,bootstrap@3.3.6', false, false, false);`?

Also, do you have `'assets.js_combine'` enabled in your config file? The code which seems most likely to cause this problem should only run when assets are combined, but this should probably be looked into anyway.

**Comment by FlorinMotoc** [comment]
This reply took ages :)

Anyway, I don't use it like that because it don't work but I surely would want it to work.

To test this, I've created a method test_assets() in a controller with these lines:
`Template::set_view('test_assets.php');
Template::render('test_assets');`
Be sure to have Template, Assets already loaded.

In the views directory, create an empty file test_assets.php for the set_view().
In the theme directory, I've created a file named 'test_assets.php' with only this line:
`echo Assets::external_js('//cdn.jsdelivr.net/g/jquery@2.2.3,bootstrap@3.3.6', false, false, true);`

As I have a file assets/global.js and I don't want to include that, I've put the last parameter of external_js() to true.

I've also tried with `Assets::add_js()` + `echo Assets::js()`, or directly `echo Assets::js(array('//cdn.jsdelivr.net/g/jquery@2.2.3,bootstrap@3.3.6'))`

Anyway, I've tried all possibilities without success.

Everytime, the output is:

`<script src='//cdn' type='text/javascript'></script>`

Also, the config/application.php is:
`$config['assets.js_minify'] = false;`
`$config['assets.js_combine']  = false;`
Tried modifing these, still the same output.

**Comment by mwhitneysdsu** [comment]
This may not be relevant, but the argument to `Template::set_view()` should not include the `.php` extension.

It looks like the issue traces back to the `find_files()` method in the Assets library:
https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/libraries/Assets.php#L1136

The same issue exists in the `generate_file()` method:
https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/libraries/Assets.php#L1014

My initial guess at a solution would be to check to make sure `$pos` is at the end of the string, or use a different function to determine whether the string ends with the file extension.
