### ISSUE TITLE
tut_blog: data migration - column key

### ISSUE THREAD

**Issue by Namluu** [ci-bonfire/Bonfire#1195]
I'm doing "Setup the Database" in http://cibonfire.com/docs/developer/tut_blog.
Then I meet: 
```
A Database Error Occurred

Error Number: 1075

Incorrect table definition; there can be only one auto column and it must be defined as a key

CREATE TABLE `bf_posts` ( post_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, body TEXT NULL, created_on DATETIME NOT NULL, modified_on DATETIME NULL, deleted TINYINT(1) NOT NULL DEFAULT 0 ) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci

Filename: E:/xampp/htdocs/Bonfire/bonfire/modules/blog/migrations/001_Initial_tables.php

Line Number: 19
```
Note that my code: `$this->dbforge->add_key('post_id', TRUE);` is above the line `$this->dbforge->create_table('posts');`
have any suggest? thanks.

**Comment by Namluu** [comment]
Okay, I think this it CI forge's issue
There is a conflict between primary key and auto_increment setting.
I have make a hotfix in DB_forge.php::_process_primary_keys() - remove the line `unset($this->primary_keys[$i]);`

**Comment by OAVHomeAdmin** [comment]
Where is the DB_forge.php File?
