### ISSUE TITLE
Problema usando jQuery

### ISSUE THREAD

**Issue by carlos860920** [ci-bonfire/Bonfire#1201]
Hola no puedo usar jQuery en las vistas, he agregado en el constructor los siguiente pero sigue sin trabajarme, agradeceria la ayuda de alguien.
Assets::add_js('jquery-1.7.2.js');
saludos

**Comment by mwhitneysdsu** [comment]
I'm going by the following from Google Translate:

> Hi I can not use jQuery in view, I added the following in the constructor but still not work 
> I would appreciate someone's help.
> Assets :: add_js ('jquery-1.7.2.js');
> Cheers

The default theme includes jQuery in the following file:
https://github.com/ci-bonfire/Bonfire/blob/develop/public/themes/default/footer.php

The actual code that includes it looks like this:

```php
<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo js_path(); ?>jquery-1.7.2.min.js"><\/script>');</script>
    <?php echo Assets::js(); ?>
```

So, unless you've modified the theme to remove this code, you should not need to add the script via `Assets::add_js();`.

On the other hand, if you have removed that code, `Assets :: add_js ('jquery-1.7.2.js');` should work, as long as you still have a call to `echo Assets::js();` somewhere in the views used to build your page. If this is not working, you need to locate the script output in your page source when you're viewing the page and determine where it is looking for the script.
