### ISSUE TITLE
Can not disable profiler

### ISSUE THREAD

**Issue by jhon100** [ci-bonfire/Bonfire#1206]
I just install the 0.8.3 version and I can not disable the profiler display. I have unchecked all options (Administrator, User, Editor and Developer) in the permissions matrix - Bonfire.Profiler.View. But is still displaying, for User role too. It would be a bug? Or how do I display it only for the Administrator role ?

**Comment by mwhitneysdsu** [comment]
Does the profiler go away when you navigate to an admin page (anything which uses the `Admin_Controller`)? Does it go away if you change the environment?

**Comment by jhon100** [comment]
No, it only disappear on the home page of frontend. Could be because I'm in localhost?

**Comment by mwhitneysdsu** [comment]
The front-end profiler should be controlled by `'site.show_front_profiler'`, which is set using the checkbox labelled "Show Front End Profiler?" in the "Developer Settings" tab of the site settings (`admin/settings/settings`).

If the front-end profiler is enabled, the only things that will disable the profiler are:
- an AJAX request,
- a CLI request, or
- setting the environment to `'production'` or `'testing'`

The front-end profiler is basically on or off, and when it's on, it overrides the admin profiler, as well.

When the front-end profiler is disabled, the admin profiler will only be displayed if:
- `'site.show_profiler'` is true (controlled by "Show Admin Profiler?" in the site settings
- the current user has the `'Bonfire.Profiler.View'` permission
- the environment is set to `'development'`

The best way to change this behavior if you want to avoid changing the `Base_Controller` and/or `Admin_Controller` directly would be to override the showProfiler() method in your own controller(s). You can copy the existing method from `Base_Controller` and refer to the way the method is called by the constructors in `Admin_Controller` and `Home_Controller` for an idea of how to limit the profiler. The easiest way to just add the permission check into the method would probably be something like this:

```php
    protected function showProfiler($frontEnd = true)
    {
        if (is_cli() || $this->input->is_ajax_request()) {
            return;
        }

        if ($frontEnd && ! $this->settings_lib->item('site.show_front_profiler')) {
            return;
        }

        if (! $this->auth->has_permission('Bonfire.Profiler.View') {
            return;
        }

        $this->load->library('Console');
        $this->output->enable_profiler(true);
    }
```

or you could do something like this:


```php
    protected function showProfiler($frontEnd = true)
    {
        if (! $this->auth->has_permission('Bonfire.Profiler.View') {
            return;
        }

        parent::showProfiler($frontEnd);
    }
```

**Comment by jhon100** [comment]
Ok solved, thank you for your help.
