### ISSUE TITLE
Wrong sitenav links presentation (Showing 'Sign in' to logged in user)

### ISSUE THREAD

**Issue by jhon100** [ci-bonfire/Bonfire#1207]
Sorry for one more issue...
I followed the tutorial on adding a Blog module and put a link to the blog page in the public/themes/default/_sitenav.php file as follows: 

```php
   <ul class="nav nav-pills pull-right">
        <li <?php echo check_class('home'); ?>><a href="<?php echo site_url(); ?>"><?php e(lang('bf_home')); ?></a></li>

>>> <li><a href="<?php echo site_url(); ?>/blog"><?php echo 'Blog' ?></a></li>

        <?php if (empty($current_user)) : ?>
        <li><a href="<?php echo site_url(LOGIN_URL); ?>">Sign In</a></li>
        <?php else : ?>
        <li <?php echo check_method('profile'); ?>><a href="<?php echo site_url('users/profile'); ?>"><?php e(lang('bf_user_settings')); ?></a></li>
        <li><a href="<?php echo site_url('logout'); ?>"><?php e(lang('bf_action_logout')); ?></a></li>
        <?php endif; ?>
    </ul>
```

If I am logged in and in 'Home', the links displayed are : 
Home | Blog | My Profile | Sign Out

But if I access 'Blog' page, the links displayed are:
Home | Blog | Sign In
Why 'Sign In' if I'm logged in? In the profiler I see :
auth_custom: jhon
logged_in: true

>v0.8.3

**Comment by mwhitneysdsu** [comment]
In order to make the `$current_user` variable available from a controller which extends `Front_Controller` without requiring the user to log in, you need to load the auth library before the parent constructor is called in your controller's constructor:

```php
public function __construct()
{
    $this->load->library('users/auth');
    parent::__construct();
    $this->load->model('post_model');
}
```

**Comment by jhon100** [comment]
Solved, thank you very much. I am excited about Bonfire ... A great tool and excellent support. :)
