### ISSUE TITLE
not escaping description of new module

### ISSUE THREAD

**Issue by jayjfletcher** [ci-bonfire/Bonfire#1213]
Hi guys, love what you've done here with bonfire and just want to contribute. 

I noticed the following bug:

When creating a new module and editing the advanced options, the fields are not escaped before saving to the configuration file and language files 

I noticed this when I ran into an error after using a single quote within the module description field.

**Comment by mwhitneysdsu** [comment]
Since the variables are potentially used for different purposes in each portion of the process, the variables will need to be escaped either in the individual methods in the Modulebuilder library, just before loading the view (e.g. `buildConfig()` and `buildLang()`), or in the views themselves.
