### ISSUE TITLE
Asset Grouping

### ISSUE THREAD

**Issue by maczdata** [ci-bonfire/Bonfire#1215]
Good day, am not really a pro with php, i needed to know how to group assets like js/css in bonfire. it would definitely safe some consumtion.

**Comment by mwhitneysdsu** [comment]
You can set a couple of configuration options to tell the Assets library to combine CSS or JS files into a single file. The options are documented here: https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/libraries/assets.md#assetscss_combine
