### ISSUE TITLE
Errors (bugs?) on default assets

### ISSUE THREAD

**Issue by jhon100** [ci-bonfire/Bonfire#1216]
I'm using v0.8.4-dev version and noticed that in the admin panel, the bootstrap javascript is being duplicated:
```html
<script src='(...)/themes/default/js/bootstrap.min.js' type='text/javascript'></script>
<script src='(...)/themes/admin/js/bootstrap.min.js' type='text/javascript'></script>
```
I also noticed that is being included the 'default' css in addition to the 'admin' css:
```html
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/css/bootstrap.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/css/bootstrap-responsive.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/default/screen.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/screen.css' media='screen' />
```
From what I saw, the inclusion of default css does not seem necessary. I solved the problem (only the css problem) changing in the \themes\admin\header.php file:
```php
echo Assets::css (null, true);
 // to
echo Assets::css (null, 'screen', TRUE);
```
As exemplified in the documentation, in 'Working with Assets >> Passing By Inheritance'. However, when adding a CSS by the controller, such as

```php
public function charts()   {
    $this->auth->restrict($this->permissionCreate);
    Assets::add_css('//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css');
    Template::set('toolbar_title', 'Charts');
    Template::render();
}
```
The default admin CSS link is being duplicated:
```html
<link rel='stylesheet' type='text/css' href='//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/screen.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/css/bootstrap.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/css/bootstrap-responsive.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/screen.css' media='screen' />
```
How could resolve these errors with default assets?

**Comment by mwhitneysdsu** [comment]
It looks like you're reporting two different issues, unless your last example has a typo in the directory name of one of the screen.css files.

For the first part, the issue is that the default themes aren't designed to properly handle asset inheritance. Ideally, the `admin/screen.css` would only contain what needs to be added to `default/screen.css`, and the bootstrap files should probably be in the central assets directory, rather than the themes, unless you wanted to change something in the bootstrap CSS/JS based on the theme.

However, if you absolutely don't need any of the default assets in your admin theme, you can modify your [Admin_Controller](https://github.com/ci-bonfire/Bonfire/blob/develop/application/core/Admin_Controller.php#L75) to change the set_theme call from this:

```php
Template::set_theme($this->config->item('template.admin_theme'), $this->config->item('template.default_theme'));
```

to something like this:

```php
Template::set_theme($this->config->item('template.admin_theme'), 'theme-that-does-not-exist');
```

As long as the second argument is not empty and is not a valid path to a theme, the default theme will no longer be in the search path when it's loading assets and views.

If the last example is not a typo, it will probably take a lot more work to figure out what's causing the `admin/screen.css` to be output twice.

**Comment by jhon100** [comment]
Thank you, your suggestion solved the problem of javascript bootstrap duplicated files (one of admin and other of default).
What I meant in the last example with 'default admin CSS' was just about the file 'admin/screen.css', was not a typo. This error remains and could not find the error source. Any idea what may be the error source?

**Comment by mwhitneysdsu** [comment]
My best guess, without taking some significant time to look at the code, would be that you may be making multiple calls to `echo Assets::css()` with an empty first argument (`null`, an empty string, etc.) and you haven't disabled the `$globals` property (by calling `Assets::setGlobals(false)`). This would most likely cause the method to add the css file named for the second argument (which defaults to `'screen'`) to the output.

The only other thing I could think of would be if the screen.css entry was added by including it in a call to `add_css()`.

**Comment by jhon100** [comment]
I'll see if I can investigate further but your last guess seems to make sense because when I add two css files by the controller appear three 'admin/screen.css' files
```html
<link rel='stylesheet' type='text/css' href='//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/screen.css' media='screen' />
<link rel='stylesheet' type='text/css' href='//cdn.jsdelivr.net/chartist.js/test.min.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/screen.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/css/bootstrap.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/css/bootstrap-responsive.css' media='screen' />
<link rel='stylesheet' type='text/css' href='(...)/themes/admin/screen.css' media='screen' />
```html

**Comment by jhon100** [comment]
The problem was in the check order, see the test:
```php
public static function add_css($style = null, $media = 'screen', $prepend = false)
    {
        if (empty($style)) {
            return;
        }

        // Debugging issues with media being set to 1
        if ($media == '1') {
            $media = 'screen';
        }
1 -     var_dump($style);
        // Add a string
        if (is_string($style)) {
            $style = array(
                'field' => $style,
                'media' => $media,
            );
        }
2 -    var_dump($style);
        // Add an array
        $stylesToAdd = array();
        if (is_array($style)) {
            foreach ($style as $file) {
                $stylesToAdd[] = array(
                    'file'  => $file,
                    'media' => $media,
                );
            }
        }
3 -    var_dump($stylesToAdd );

        if ($prepend) {
            self::$styles['css'] = array_merge($stylesToAdd, self::$styles['css']);
        } else {
            self::$styles['css'] = array_merge(self::$styles['css'], $stylesToAdd);
        }
    }
```
The output was
```php
1 -    
string(54) "//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css"

2 -    
array(2) {
  ["field"]=>
  string(54) "//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css"
  ["media"]=>
  string(6) "screen"
}

3 -    
array(2) {
  [0]=>
  array(2) {
    ["file"]=>
    string(54) "//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css"
    ["media"]=>
    string(6) "screen"
  }
  [1]=>
  array(2) {
    ["file"]=>
    string(6) "screen"
    ["media"]=>
    string(6) "screen"
  }
}
```
So I changed the function to
```php
 public static function add_css($style = null, $media = 'screen', $prepend = false)
    {
        if (empty($style)) {
            return;
        }

        // Debugging issues with media being set to 1
        if ($media == '1') {
            $media = 'screen';
        }

        // Add an array
        $stylesToAdd = array();
        if (is_array($style)) {
            foreach ($style as $file) {
                $stylesToAdd[] = array(
                    'file'  => $file,
                    'media' => $media,
                );
            }
        }
		
		if (is_string($style)) {
            $stylesToAdd[] = array(
                'file' => $style,
                'media' => $media,
            );
        }

        if ($prepend) {
            self::$styles['css'] = array_merge($stylesToAdd, self::$styles['css']);
        } else {
            self::$styles['css'] = array_merge(self::$styles['css'], $stylesToAdd);
        }
    }
```
I tested with single css file and with array. All Is working as expected.

**Comment by mwhitneysdsu** [comment]
Thank you for the help tracking this down.

Although your version should work, it's not so much that the order of the operations was wrong as it was that the handling of the string version was incorrect (in multiple ways). If you change the `if (is_string($style))` portion to the following, it appears to fix it without having to move the code around:

```php
        // Add a string
        if (is_string($style)) {
            $style = array($style);
        }
```

Fortunately, I was able to identify two pages in my own site which used nearly the same `add_css()` call in the controller, yet one of the pages displayed the same behavior and the other did not. The one which did not passed `'all'` as the second parameter, and the system couldn't find an 'all.css' file in the theme, so it didn't output a link element for the file.

I've been doing a little more testing with the various different calls to `add_css()` on my site, but I should be able to push this change shortly.
