### ISSUE TITLE
getting Error in Installation

### ISSUE THREAD

**Issue by GaneshKandu** [ci-bonfire/Bonfire#1222]
Getting Error After Clicking on Next Button

**A PHP Error was encountered**

Severity: Runtime Notice

Message: Only variables should be assigned by reference

Filename: migrations/018_User_meta_move.php

Line Number: 173

Backtrace:

File: [[Bonfire_Root]]/bonfire/migrations/018_User_meta_move.php
Line: 173
Function: _error_handler

File: [[Bonfire_Root]]/bonfire/modules/migrations/libraries/Migrations.php
Line: 508
Function: call_user_func

File: [[Bonfire_Root]]/bonfire/modules/migrations/libraries/Migrations.php
Line: 332
Function: version

File: [[Bonfire_Root]]/bonfire/libraries/Installer_lib.php
Line: 375
Function: install

File: [[Bonfire_Root]]/bonfire/controllers/Install.php
Line: 103
Function: setup

File: [[Bonfire_Root]]/public/index.php
Line: 308
Function: require_once

**Comment by mwhitneysdsu** [comment]
Does changing line 173 of the `018_User_meta_move.php` file to this:

```php
$backup = $this->dbutil->backup($prefs);
```

fix the issue?
