### ISSUE TITLE
Installing issue with virtual host

### ISSUE THREAD

**Issue by royalneo** [ci-bonfire/Bonfire#1227]
Dear all,

I installing CIBonfire on my hosting but I rented shared hosting and i can't creating a virtual hosting because I'm a user not admin of this server.

So I can't install CIBonfire on my hosting. Can anybody have sollution for this issue?

Thanks very much for your helps.

**Comment by Reconix** [comment]
In the documentation "Reverting To Traditional Structure"
[http://cibonfire.com/docs/developer/site_structure](http://cibonfire.com/docs/developer/site_structure)
