### ISSUE TITLE
Usage of lang() in header & footer

### ISSUE THREAD

**Issue by code42fr** [ci-bonfire/Bonfire#1234]
Hello,

we're newbie with bonfire, we use v 0.8.1.

We have a created a new public interfarce and we can't add the lang files ? We use french language.

What's the include fonction to take ? is there a helper to declare ?

**Comment by mwhitneysdsu** [comment]
The language helper is autoloaded by default, and defines the `lang()` function. If you removed the language helper from `$autoload['helper']` in `/application/config/autoload.php`, then you'll need to load the helper manually, or use `$this->lang->line()`.

**Comment by code42fr** [comment]
Thanks.


with your information, we've found the problem. We didn't define the additional language in the 'application/config/config.php' .


Eric GROULT - Code 42
________________________________
De : Mat Whitney <notifications@github.com>
Envoyé : mercredi 22 juin 2016 22:48
À : ci-bonfire/Bonfire
Cc : Eric - CODE42; Author
Objet : Re: [ci-bonfire/Bonfire] Usage of lang() in header & footer (#1234)


The language helper is autoloaded by default, and defines the lang() function. If you removed the language helper from $autoload['helper'] in /application/config/autoload.php, then you'll need to load the helper manually, or use $this->lang->line().

-
