### ISSUE TITLE
set_view not working in application (??)

### ISSUE THREAD

**Issue by mihai101** [ci-bonfire/Bonfire#1235]
Hello.

I'm trying to set a view for a controller depending on a specific `$_GET` value and I noticed that no matter what I pass to `Template::set_view()`, it always uses the view with the same name as the controller, for example, controller "Test.php" will always grab the view "test.php" no matter what. I see it works fine in "bonfire" directory but not in my "application" directory.

Template::render() doesn't seem to work either.

**Comment by silverark** [comment]
Template::render('blank') would render the blank.php template from your Theme directory. set_view() is used to show the view files in your current module. Try including the module name when setting your views so if you have a module called "invoices" and a view called "items.php" use set_view('invoices/items'). If you use subfolders in views, also include them in the path.

**Comment by mihai101** [comment]
Fixed. Hat to use `Template::set_theme()` to select the theme I'm working with, and now I can select any view from my theme.

Thanks for the help anyway.

**Comment by silverark** [comment]
You can also set the default front end and admin theme in application/config/application.php file.
```
$config['template.default_theme']	= 'default';
```
