### ISSUE TITLE
Getting "Unable to find theme layout: ajax" when trying to use jQuery GET ajax method

### ISSUE THREAD

**Issue by mihai101** [ci-bonfire/Bonfire#1237]
Hello,

I'm trying to get html contents from a theme view using jQuery:

JS code:

```
$.get(site_url + "my_controller", function(data){
    console.log(data);
});

```
And the response I get is an error page saying:

> An Error Was Encountered
> 
> Unable to find theme layout: ajax

Any ideea why I'm getting this?

**Comment by silverark** [comment]
Ajax calls will try and use an ajax layout (ajax.php) from your theme folder. Just copy the following file to your theme folder: https://github.com/ci-bonfire/Bonfire/blob/develop/public/themes/admin/ajax.php

It simply prints out the content of your page. It's quite clever as you can load your content within a normal page, or load it by ajax and it will just show the modular view file (without the header and footer).
