### ISSUE TITLE
Undefined property: CI::$auth (Simple Blog Demo)

### ISSUE THREAD

**Issue by marywisher** [ci-bonfire/Bonfire#1247]
Hi, I'm a fisher.
I found a bug in "A Simple Blog Tutorial" in the official blog(http://cibonfire.com/docs/developer/tut_blog).
v0.8.3
The $_SESSION['user_id'] is exist.
The _sitenav.php in the theme, could not get $current_user, or $this->auth.
Did I miss something?

**Comment by silverark** [comment]
The tutorial uses the Front_Controller which doesn't load the Auth library or call set_current_user() in the base controller. 

When building your app, if you need the user to be authenticated (or you need the user object) use the Authenticated_Controller instead of the Front_Controller.

**Comment by marywisher** [comment]
I see!! Thanks!

**Comment by mwhitneysdsu** [comment]
I know this is already closed, but I highly recommend using either the tutorial which you downloaded with Bonfire, usually accessible via something like:
http://localhost/docs/developer/start_here/tut_blog

or use the one here on GitHub: 
https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/start_here/tut_blog.md

I'm not sure when the one on the website was last updated.
