### ISSUE TITLE
How to upgrade to latest version of CodeIgniter

### ISSUE THREAD

**Issue by MasterPumpkin** [ci-bonfire/Bonfire#1256]
Hi,

are there any possibilities to upgrade Bonfire to latest version of CodeIgniter?

Thank you very much for your reply....

**Comment by lonnieezell** [comment]
I'm looking into that upgrade this week and will try to get the development branch updated ASAP.

**Comment by lonnieezell** [comment]
Fixed in 0b7fc4ae27bb6dcea39d5dd3ff1fc71318c75a6d
