### ISSUE TITLE
Custom Module using Bonfire CI on Cpanel

### ISSUE THREAD

**Issue by sranasir** [ci-bonfire/Bonfire#1257]
I have developed my own module using bonfire on CI. The application worked without a glitch until I deployed it on Cpanel. It works well till the built in controllers that render the login page etc. As soon as I try to hit the pages of my module, it gives me a 404 error.

I have edited .htaccess in the root directory, but I am not sure what to put in .htaccess in Bonfire_root/public. I suspect the problem lies here but I am unable to troubleshoot successfully.

**Comment by silverark** [comment]
There is a .htaccess file already available:
https://github.com/ci-bonfire/Bonfire/blob/develop/public/.htaccess
When deploying, sometimes hidden files (such as the .htaccess file) aren't copied across. Do you have the file linked above on your server? The other thing is that mod_rewrite has to be enabled, but if oyur using cPanel I'm guessing that will already be configured.

**Comment by sranasir** [comment]
I finally got the problem solved after wandering around for a few days. I had everything according to what you mention. 
The issue was that my controller file names were in lowercase. I made the first letter capital and it worked.
I am surprised that no one has mentioned this quirk anywhere.
