### ISSUE TITLE
/install 404 error on 0.9.0-dev installation

### ISSUE THREAD

**Issue by senoadiw** [ci-bonfire/Bonfire#1260]
Hi,

I tried installing Bonfire 0.9.0-dev (with CI 3.1.3) on an windows Ampps installation running PHP 5.6.21 by setting up a virtualhost called bonfire.local and got a 404 error when redirected to /install. The way I got the installation page to run was by copying Install.php from the bonfire_root/bonfire/controllers/ to bonfire_root/application/controllers/ (the dir with Home.php). Also during table creation there was an error when running the 044_Update_ci3_sessions.php migration saying the table ci3_sessions does not exist (but bf_ci3_sessions table exists). Setting 'dbprefix' to '' in config/database.php allowed the installation to complete successfully.

Edit: upon checking the code [this line](https://github.com/ci-bonfire/Bonfire/commit/318420c5afc08e67b7e9f141029f4d6c232a707b#diff-dbd107884e29ff42e666a8b4fcd91a28R405) evaluates to true when looking for Install.php. Also [line 411](https://github.com/ci-bonfire/Bonfire/commit/318420c5afc08e67b7e9f141029f4d6c232a707b#diff-dbd107884e29ff42e666a8b4fcd91a28L411) which checks in BFPATH seems to be removed?

Cheers

**Comment by MasterPumpkin** [comment]
Hi,

thank you very much, your approach is definitely working..  :-)

**Comment by silverark** [comment]
@lonnieezell Just cloned v0.9.0-dev today and this still have the same issue where it won't load the installer. See pull request above. Just applied it and it started working.

Cheers.

**Comment by lonnieezell** [comment]
@silverark You're right. The PR isn't asking to pull into this repo, though, it's pointing to Silverark's. Now that we've updated to 3.1.6, we need to do the same thing, though, so a PR would be welcome for that.
