### ISSUE TITLE
Bonfire 0.9 - Bootstrap 3

### ISSUE THREAD

**Issue by Reconix** [ci-bonfire/Bonfire#1286]
Have started updating the bootstrap branch to 0.9

If anyone else has already started this please let me know.

Currently, I'm updating from 0.7-dev (judging by the index) to 0.9 (current develop branch) 
if this proves to be too much of a hassle I'll probably just dump what I've done and start again from 0.9 and add what's needed.

Will be trying to including what dgorbash has done too. I would've used that as a starting point but since it didn't get merged I can only assume no one had the time to go through all the changes.

Should probably also be noted I'll be updating jQuery, DataTables etc to the latest versions too.

I very much doubt this'll get merged into the core branch so leaving this "Issue" open as a reference for anyone else wanting to update.

**Comment by lonnieezell** [comment]
I'm all for having Bootstrap updated. It was my understanding the previous attempt never got finished, but Matt was maintaining the project at the time so I don't recall all of the details.

**Comment by DarkestEver** [comment]
Do we have stable release for 0.9 which work perfectly on php 7+. I tried using branch - dev and 0.8 but both have lots of issues on php 7+

**Comment by Reconix** [comment]
I've just been playing around with 0.9 on PHP 7.1 and no problems yet, however, if you're using 7.2+ though, you'll run into a couple problems, nothing major though ( Quick Fixes )
About to update to the latest version of CI, will do a pull request once finished.
Also on the topic of this thread, looking back it seems I had problems updating DataTables, would love to give this a bash again on the weekend.

**Comment by pascut** [comment]
I saw that the develop branch was updated 10 days ago and the CodeIgniter 3.1.9 is the main feature. What about Bootstrap 3? 

Reconix, please share your code with me, I want to help you with the integration of Bootstrap 3 and add support for Bootstrap 4. You should submit a pull request with your current changes and maybe Lonnie will update the branch, "bootstrap3", or maybe create a new one.

How different is your solution from this tree: https://github.com/ci-bonfire/Bonfire/tree/bootstrap3 ?

Thanks.

**Comment by cosmomathieu** [comment]
@pascut and @Reconix I'd recommend going with Bootstrap4 (B3) since it has already been released. B3 is great, but why waste the time? By time you get done completely implementing B3 it might be outdated.

In either case, I'd be happy to help with the B3 or B4 upgrades. Send me a link to the repo as well. Thanks!

**Comment by boblennes** [comment]
@cosmomathieu you are right BS4 is the way to go. You might be able to glean some code from my Ignition Go https://github.com/ci-blox/Ignition-Go project as I have brought it up to use Bootstrap 4, and I'm using several Bonfire born libraries (such as the template library).  I had done a bootstrap3 fork of Bonfire, but I don't know if it is still there.

**Comment by Reconix** [comment]
You guys are totally right, bootstrap 4 is the way to go if sticking with boostrap, it now plays well with others too.

PS @boblennes : Nice work on Ignition Go.
