### ISSUE TITLE
Copying Bonfire install from live environment to MAMP?

### ISSUE THREAD

**Issue by dabockster** [ci-bonfire/Bonfire#1289]
Hey everyone,

I'm trying to copy a Bonfire app from a live server to MAMP. I have the database recreated and all the files are copied straight from the site's repo. However, whenever I try to load the localhost address in MAMP, the MAMP installation of Bonfire redirects the browser back to the live environment.

Is there a URL string that I'm missing somewhere? How do I set the URL so that it will load on my test environment?

**Comment by silverark** [comment]
Look in the following file for the url: application/config/config.php

Also look for a config file in the 'development' or 'production' folder in the same location.  Ideally you would copy the config file into the development folder.

If you are still having issues look in the .htaccess file in the 'public' folder to see if there are any redirects that have been added.

**Comment by dabockster** [comment]
Yep, looks like it's an .htaccess issue. Thanks for the help.
