### ISSUE TITLE
Problem with special character in Route

### ISSUE THREAD

**Issue by matheusdelima** [ci-bonfire/Bonfire#1290]
Hello guys,

I am developing a web application and found the following problem:
When i access my controller **Uploads** with segment **anything.docx** he return 404 page, but when i access without **.docx** he found the controller, How do I solve it?

Sorry my bad English,
Thank you!

**Comment by matheusdelima** [comment]
?

**Comment by silverark** [comment]
Can you show the full URL you were using? What's your set up? Are you using WAMP, MAMP, LAMP on ubuntu?

I have a files module that serves docx files without any issue.

Also, have you put anything special in your routes file?

**Comment by matheusdelima** [comment]
There is a problem on XAMP, in other servers is working fine.
