### ISSUE TITLE
Fatal error: Uncaught Error: Out of memory  

### ISSUE THREAD

**Issue by Cheror** [ci-bonfire/Bonfire#1296]
Fatal error: Out of memory (allocated 920649728) (tried to allocate 12288 bytes) in C:\www\htdocs\www\bonfire\application\third_party\MX\Loader.php on line 228

Fatal error: Out of memory (allocated 920649728) (tried to allocate 32768 bytes) in C:\www\htdocs\www\bonfire\bonfire\ci3\core\Exceptions.php on line 1

Fatal error: Out of memory (allocated 920649728) (tried to allocate 12288 bytes) in C:\www\htdocs\www\bonfire\bonfire\ci3\database\drivers\mysqli\mysqli_driver.php on line 391

Fatal error: Uncaught Error: Class 'CI_Exceptions' not found in C:\www\htdocs\www\bonfire\bonfire\ci3\core\Common.php:210 Stack trace: #0 C:\www\htdocs\www\bonfire\bonfire\ci3\core\Common.php(636): load_class('Exceptions', 'core') #1 [internal function]: _error_handler(2, 'Unknown: Cannot...', 'Unknown', 0, NULL) #2 {main} thrown in C:\www\htdocs\www\bonfire\bonfire\ci3\core\Common.php on line 210

**Comment by silverark** [comment]
Was this in teh initial installation?

Just increase your memory limit in you php.ini file. There will be different ways of doing that based on your server. Are you using WampServer?

**Comment by Cheror** [comment]
.yea, first installation, using wamp

**Comment by silverark** [comment]
https://stackoverflow.com/questions/37936399/increase-memory-limit-on-wamp

You can find the file as per the link above or there may be a link to it in your icon tray. "Wampmanager tray icon -> PHP -> php.ini". Just search for memory_limit in that file.

**Comment by Cheror** [comment]
I increased memory limit to 512 in php.ini , still i cant solve the problem.
Thanks for repsonse

**Comment by silverark** [comment]
That's because the error above says it was over 900MB. You shouldn't really need that much memory, but just knock it up to 2000 for the installation and then put it back down. 

Did you use the M symbol too for Megabytes? Set it to 2000M then do the install, then reduce it to 250M afterwards.

**Comment by silverark** [comment]
Once you have changed the php.ini file, make sure you restart the server too. Use phpinfo() on a page too to check the memory limit has updated: http://php.net/manual/en/function.phpinfo.php

**Comment by Cheror** [comment]
Thanks Silverak, it is solved.

**Comment by christoferd** [comment]
If it's solved, then mark it as solved, close the issue.

Why would any web install need 900M?? :-o

**Comment by Cheror** [comment]
Thanks alot, isssue solved.
