### ISSUE TITLE
RichText Editor in TextArea from Admin Panel is not working properly!

### ISSUE THREAD

**Issue by AxDSan** [ci-bonfire/Bonfire#1304]
So when I try to do a new module, and add the following configurations to the table textarea it doesn't works, when I'm in the create view, it doesn't really shows the textarea as the editor I chose...

![](https://i.imgur.com/Qd7x2fi.png)

![](https://i.imgur.com/rgfY9R1.png)

is there something else I need to configure prior using the RichText Editors?

**Comment by GintaWahyudi** [comment]
https://medium.com/@JosefNuhlicek/how-to-implement-a-textarea-wysiwyg-editor-in-codeigniter-bonfire-d6ac2600f69a

**Comment by AxDSan** [comment]
Thank you so much!
