### ISSUE TITLE
BF_Router Bonfire Update issue from 0.7.X to 0.7.8 and CI3

### ISSUE THREAD

**Issue by rajjagani021** [ci-bonfire/Bonfire#1312]
I have updated the Bonfire into my existing code from version 0.7 . to 0.7.8 and Codeigniter 3. Everything looks good but when I have run the site, first I am getting the error 

`Fatal error: Access level to BF_Router::_set_default_controller() must be public (as in class CI_Router) in /Applications/MAMP/htdocs/Bonfire-master/bonfire/core/BF_Router.php on line 306`

But when I change all the method from **Protected** to **Public**  in BF_Router.php. I am getting 404-page error on every route.

 As I have investigated a little bit further I found that It can't find default class and method to navigate the page.

Any help would be appreciated. 

![bf_router_issue](https://user-images.githubusercontent.com/4434991/50137001-ce05b380-02bf-11e9-9017-0d78034d88ac.png)

Thanks

**Comment by silverark** [comment]
If you're using CI3, maybe try using the v0.8.x or 0.9 branch?

The dev barach has had the most recent updates. 

What version of CI3 did you drop in?

**Comment by rajjagani021** [comment]
I have taken the pull from **develop** branch and Current **CI version is 3.1.9.**

**Comment by silverark** [comment]
Looks like 5 months ago those changes will help: "CI3 core Updates & Fixes 3.1.9"

Are you still seeing the same error messages?

You may need to capitalise the controller names you are using. There are a few changes if you are changing your CI version. 

https://www.codeigniter.com/userguide3/installation/upgrade_300.html

**Comment by rajjagani021** [comment]
@silverark  

I have replaced the Bonfire folder from develop branch to 0.8.3 and updated the the changes like making controller name with UCfirst case. So It's solved the issue of routing but not its giving some issue of BF_Model as per attached screenshot.

@jaycreate : I am pointing to public folder.

![bf_model](https://user-images.githubusercontent.com/4434991/50156316-851c2200-02f4-11e9-9215-2b7cc61d4a86.png)
![bonfire_model](https://user-images.githubusercontent.com/4434991/50156317-851c2200-02f4-11e9-8c07-e57fb2a79f5d.png)

**Comment by rajjagani021** [comment]
The basic issue is resolved as I need to replace the bonfire folder with 0.8.3 branch.
