### ISSUE TITLE
Error with Bonfire + XAMPP

### ISSUE THREAD

**Issue by rajkumarpb** [ci-bonfire/Bonfire#1314]
Copied the folder, changed the base URL & Database details. After navigating to /bonfire, getting the below URL. If I add the below line in .htaccess in XAMPP folder, getting blank page. What I am doing wrong? Please help me guys!

Your Web Root should be set to the public folder, but it's not. It's pointing to the Bonfire Root folder.

See below for an example of how your site should be set up in Apache:

<VirtualHost *:80>
    DocumentRoot "[...]/htdocs/Bonfire_Root/public"
    ServerName Bonfire.Root
    ServerAlias Bonfire.Root.local
</VirtualHost>

**Comment by LoneCoderLab** [comment]
Hello,

for me, the best way how to successfully install Bonfire is reverting to traditional site structure - [http://cibonfire.com/docs/developer/site_structure (http://cibonfire.com/docs/developer/site_structure) - bottom of the page.

Try it ...

**Comment by rajkumarpb** [comment]
Thanks guys! It's working now.
