### ISSUE TITLE
Can not login to admin when site is turned off

### ISSUE THREAD

**Issue by og-shawn-crigger** [ci-bonfire/Bonfire#337]
I noticed this awhile ago and forgot about it, and someone posted it on the forums.

If you turn the site off, you can not login to the admin section.

**Comment by markbratanov** [comment]
Is there a solution on how to enter when locked out? I've set site.status to 0 in the database, but I still can't turn off site maintenance. Is there another part I'm missing, perhaps in a config file?

**Comment by mwhitneysdsu** [comment]
If you have a version of Bonfire installed which includes 317c3ca69061d77555454df844af29ff1f6958cf (including /application/hooks/App_hooks.php), as long as your login page is included in the $allowOffline array, you should be able to login to the site by navigating to any page which requires login.
