### ISSUE TITLE
Images controller saves Image as a Requested Page

### ISSUE THREAD

**Issue by og-shawn-crigger** [ci-bonfire/Bonfire#417]
Minor bug, if you use the dynamic images controller to resize your images ( +1 Lonnie love the caching ) and try to login you get redirected to a image.  Nothing major but could cause confusion to end users.

**Comment by kjwm** [comment]
Hello, i am not getting this right. can some one guide me on how to resize. i have: <img src="http://mysite/index.php/images?photo.jpg&amp;&amp;assets=uploads"> but it gives me no image.

**Comment by kjwm** [comment]
Sorry for the above mistype. I am trying to resize an image using:
<code><img src="http://mysite/images?photo.jpg</code>

**Comment by kjwm** [comment]
Hello, i am not getting this right. can some one guide me on how to resize. i have: 
img src=" site_url() . 'images?yourimage.jpg&asset=assets/images&size=100&crop=true" />
 but it gives me no image.
