### ISSUE TITLE
Custom Modules not showing in context menus 

### ISSUE THREAD

**Issue by jfox015** [ci-bonfire/Bonfire#437]
I pulled the latest develop branch update Thursday after my password branch was merged in and once I integrated my custom context updates and dropped in my custom modules, none of them (save for Sean's Navigation module) appear in the context drop down menus anymore.

Looking through the code, I noticed the default context/module permissions in _bonfire/application/config/application.config_ were removed. I also noticed that some permissions that used to be "Site._" are now "Bonfire._" though there are mixed instances of both throughout the code in the core_modules folder (I've seen differences in users and database most specifically).
So curious if I screwed something u[p or there's a migration issue up to the most up to date code.

Here are two versions, an earlier 0.6 build with the menus:

![Working Nmenus](http://uabl.aeoliandigital.com/images/ootp_forums/errror_context.png)

and my latest version on localhost:

![Working Nmenus](http://uabl.aeoliandigital.com/images/ootp_forums/errror_context_local.png)

**Comment by theCrius** [comment]
Thank you Buonzz. Your solution fixed the problem.

Seems like the internal hooks system doesn't work properly and honestly the development team should at least keep the [tutorial](http://cibonfire.com/docs/developer/tut_blog) updated because at the moment I'm struggling with nearly every section due to bugs and outdated instruction.

No wonder if bonfire it's not taking ground.

**Comment by mwhitneysdsu** [comment]
The website is being overhauled, so hopefully the updated docs will be included when the new site is online. In the meantime, you might want to try [the tutorial](https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/tut_blog.md) here on GitHub, or in your own installation, which should be accessible using an address similar to http://localhost/docs/developer/tut_blog
