### ISSUE TITLE
[solv] : Unable to locate the model you have specified: activity_model

### ISSUE THREAD

**Issue by slegouffe** [ci-bonfire/Bonfire#49]
Just after click on "install bonfire"

"An Error Was Encountered
Unable to locate the model you have specified: activity_model"

Solution : change bonfire/application/core_modules/activities/models/Activity_model.php to bonfire/application/core_modules/activities/models/activity_model.php (the "a" letter of "activity_model.php" file name have to be in lower case).

**Comment by Durgeshpooja** [comment]
sorry for it ,but i am doing this process but error is not done
