### ISSUE TITLE
Site Settings error on Save: Security and Developer Tabs [bug] [0.7]

### ISSUE THREAD

**Issue by thinkadoo** [ci-bonfire/Bonfire#618]
The first tab: "MainSettings" saves fine. The other two tabs: "Security Settings" and "Developer Settings" both don't "save" but throw the PHP Error below when "Save" is clicked.

Update:  I get it in Chrome and Safari - but it seems to be erratic on which tabs it throws the error. Sometimes on one, then two, then all three tabs. Then on none.

PHP 5.4.4 MAMP

More detailed BackTrace
http://cl.ly/KC4d

A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: database/DB_active_rec.php
Line Number: 1407

A PHP Error was encountered
Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/Bonfire/bonfire/codeigniter/core/Exceptions.php:185)
Filename: libraries/Session.php
Line Number: 672

A PHP Error was encountered
Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/Bonfire/bonfire/codeigniter/core/Exceptions.php:185)
Filename: helpers/url_helper.php
Line Number: 542

**Comment by chiba-xp** [comment]
### asdfaf
**asfasfafs**
