### ISSUE TITLE
Module Controller Method dn't take 4 parameters?? plz give me solve for this issue

### ISSUE THREAD

**Issue by washimreza** [ci-bonfire/Bonfire#896]
first i give 2 links for understand the problem

http://localhost/ci_tvc/admin/advance/program_type_price/create/1/2/3 here create method take 3 param and its working

http://localhost/ci_tvc/admin/advance/program_type_price/create/1/2/3/4 bt this shows "404 Page Not Found"

here is the method written in controller

public function create($a, $b, $c, $d=0) { //code here }

can any 1 help me why the 4th param is not working as 4th param? is there any config to change for parameter limitation?

plz reply me i stack with that

**Comment by moxuanyuan** [comment]
The problem still exists , so sad
