### ISSUE TITLE
Question: ! defined('BASEPATH') statements

### ISSUE THREAD

**Issue by mwhitneysdsu** [ci-bonfire/Bonfire#988]
I happened to notice an issue in the CI repo regarding the BASEPATH checks at the top of the files. Specifically, the checks used more or less throughout Bonfire and in the CI 2.1.4 branch:

``` php
if (!defined('BASEPATH')) exit('No direct script access allowed');
```

were replaced in the CI 3.x branch with:

``` php
defined('BASEPATH') OR exit('No direct script access allowed');
```

Personally, I'm not a big fan of the `OR` operator, especially since it doesn't have the same operator precedence as the `||` operator (http://www.php.net/manual/en/language.operators.precedence.php), but I was wondering if it would be a good idea to adopt the updated statement (or a similar one). I have no idea when (or if) CI 3 will be officially released or if Bonfire will be able to support it as a clean upgrade, but I feel that even with the offensive `OR` operator the updated statement is a little cleaner than the older one (which fails to meet almost every coding standard you could possibly apply).

I'm not asking for a giant changeset to update the line on every file, just a "change as you go" type of policy. 

I think the same could be said of the copyright notices, especially since it's probably legally questionable to assert an extension of copyright on something that was only changed by updating the year in the copyright notice to begin with.

**Comment by cosmointeractive** [comment]
Is there a difference between the two? Like one is more secure, etc.?

**Comment by mwhitneysdsu** [comment]
In terms of the result, there is no difference. There may be a slight improvement in execution time for the line without the if statement, but I really doubt it would be noticeable, if there happened to be a difference.

The if statement happens to trigger some errors in PHP CodeSniffer when the standard is set to PSR2, but the alternative is no more compliant to the standard, it just goes unnoticed by the tool. 

Personally, I tend to think of if statements without braces as code landmines, since each instance is waiting for someone to come by and modify the code, only to have it blow up in their face. It isn't particularly likely in this location, but I don't think it sets the best example to have one right at the top of each file.

All of that said, I don't think it's particularly necessary in most locations, especially since most of the scripts are no longer in a public location by default. However, in deference to the needs of some people to put their code in public locations, it's probably best to maintain them so long as they have no negative consequences.

**Comment by cosmointeractive** [comment]
Thanks for the thorough answer.
